name: Test Workflow

on:
  workflow_dispatch:   # gjør det mulig å starte manuelt

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hei, workflowen fungerer"
